### ISSUE TITLE
Not publishing comments

### ISSUE THREAD

**Issue by ndesai15** [tomasbjerre/violation-comments-to-gitlab-lib#11]
I am running against sonar, & I have a path in Jenkins where I am exporting my sonar report.

mvn command:
mvn org.jacoco:jacoco-maven-plugin:prepare-agent
clean
install
sonar:sonar
-Dsonar.analysis.mode=analysis
-Dsonar.report.export.path=sonar-report.json

Violation Configurations:
Parser:SONAR
Pattern: target/sonar/sonar-report.json
Reporter:SONAR.

Now build completed successfully & shows 0 violation even though I can see in sonar-report.json that there some violations in that file. 

Any suggestion what could be the issue?

**Comment by tomasbjerre** [comment]
Can you attach the report file?
How did you configure the plugin?
