### ISSUE TITLE
GitLab violations on newly created large files

### ISSUE THREAD

**Issue by ateglas** [tomasbjerre/violation-comments-to-gitlab-lib#13]
I have a project that I am on-boarding on "violation-comments" and thought that the best way to show the team how it works is to duplicate one large file in the project, that has a lot of issues, and show them how pmd, cpd and spotbugs comments look like for that merge request. I was expecting to see a lot of comments in the merge request, but there were just the "control" comments (what I mean by these comments is that, in order to see that the whole pipeline is working, I first did some copy/paste in a small file just to trigger the library to comment on the merge request and to see that the whole flow works). 

Steps to reproduce:
1. Create a new branch
2. Add a large file with a at least one violation (mine was about 7.2k lines long)
3. Submit a merge request in GitLab for it
4. Run violation-comments over the project and merge request (I was using maven)

Why I think this happens:
1. If the file is large enough, GitLab does not give you the diff, but says on the merge request changes page:
> This source diff could not be displayed because it is too large. You can view the blob instead.
2. The diff string that the library is getting for this file is empty because of the size. The URL for getting the merge request changes, `$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/changes`
gives:
> {
>     "old_path": "src/main/java/com/test/SomeLargeFile.java",
>     "new_path": "src/main/java/com/test/SomeLargeFile.java",
>     "a_mode": "0",
>     "b_mode": "100755",
>     **"new_file": true,**
>     "renamed_file": false,
>     "deleted_file": false,
>     **"diff": ""**
> },
3. The newFile flag does not seem to be used anywhere, just the diff, which, because of the size, is empty. Therefore, all the violations end up in the "Will not include violations on changed files because violation reported on untouched lines" section.

**Comment by tomasbjerre** [comment]
Thanks for reporting. PR:s are welcome.

**Comment by ateglas** [comment]
The problem seems to be more convoluted than initially thought. It is not just new files where we could get empty diff from GitLab, but any large change to the same file could have this effect. There are discussions on GitLab side to provide a paging mechanism for getting even large changes, but for now that case cannot really be solved. 

The current fix is just for new files. We could do the comments for all large changes, but it would be a move from one problem case (comments not showing) to another problem case (comments showing in the whole file).
