### ISSUE TITLE
Violation comments on context lines around differences

### ISSUE THREAD

**Issue by ateglas** [tomasbjerre/violation-comments-to-gitlab-lib#15]
Some tools create quite a lot of warnings and can uncover problems that went unnoticed for a long time. In our case, we started using CheckStyle and it has quite a lot to comment about our code, almost on every line or so. This led us to notice that using commentOnlyChangedContent set to true, we still got comments on lines that were not actually touched but were in the immediate vicinity of changes.

Digging into the problem, we noticed that GitLab provides up to +/- 3 more lines of context around the actual changes. If those lines contain problems, there will be comments left for them in the merge request. Fixing those just takes the problem one step further as now the difference will contain the previous context lines, now changed content, plus another +/-3 more lines of context. Context lines coupled with a verbose checking tool tend to make the commentOnlyChangedContent property kind of useless. In the end you need to update the whole file anyways. 

I have a PR **almost** ready for this, the question I have is if we:

1. add an option along commentOnlyChangedContent, say commentOnlyChangedLines or ignoreContextLines, that we can use to keep previous behavior as is and make it possible to restrict the commented lines even further for the ones that want it
2. just change the current behavior of commentOnlyChangedContent to ignore context lines aroud differences as well. 

I'd personally go for option 2., not just because it is simpler (not in implementation but in rolling out, as you don't have 4 other projects to update: jenkins, maven, gradle and cmdline) but also because that is probably the reason why someone uses commentOnlyChangedContent in the first place. 

Let me know what you think...

**Comment by tomasbjerre** [comment]
The Bitbucket Server library has an integer that defines the context:
https://github.com/tomasbjerre/violation-comments-to-bitbucket-server-lib/blob/master/src/main/java/se/bjurr/violations/comments/bitbucketserver/lib/ViolationCommentsToBitbucketServerApi.java#L48

So setting it to 0 (or 1, I dont remember) should to what you want. So I'd like to see as solution here that is similar to what is implemented there.

Perhaps you can open a PR with what you got so far. Perhaps option `2` is same as adding a `commentOnlyChangedContentContext` and letting it default to `1`.

Also, I personally solve this problem with the [Gradle Plugin](https://github.com/tomasbjerre/gradle-scripts/blob/e285b3948998a86fd4ae0fa320d9048b4e6c7f93/src/main/resources/main.gradle#L167). By default no violations are allowed but it can be changed in the [gradle-files](https://github.com/tomasbjerre/violations-lib/blob/5fa2ec7c1852cd9749309b2ae5309ef9a7c30b9f/build.gradle#L23). And I don't accept pull requests where someone increase this number (manual review by me).

**Comment by ateglas** [comment]
Thanks for the link for the bitbucket implementation, I think we could do something similar for GitLab. Looking at the code it would look like what I would need would be commentOnlyChangedContentContext as 0, which also seems the default for Bitbucket. 

Need a bit of time to adjust for something similar with Bitbucket, but should easily be doable.
